name = "prismplay/24days_to_lose_weight"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dependencies]
scripts = { name = "jiwonz/pesde_scripts_rojo", version = "^0.1.0-rc.1", target = "lune" }
Signal = { wally = "sleitnick/signal", version = "^2.0.3" }
Knit = { wally = "sleitnick/knit", version = "^1.7.0" }
Trove = { wally = "sleitnick/trove", version = "^1.5.1" }
SimplePath = { wally = "jessekroeske/simplepath", version = "^2.2.2" }
Component = { wally = "sleitnick/component", version = "^2.4.8" }
TableUtils = { wally = "sleitnick/table-util", version = "^1.2.1" }
FastCastRedux = { wally = "rocketcamel/fastcastredux", version = "^1.0.2" }
Comm = { wally = "sleitnick/comm", version = "^1.0.1" }
Fusion = { wally = "elttob/fusion", version = "^0.3.0" }
Timer = { wally = "sleitnick/timer", version = "^1.1.2" }
ZonePlus = { wally = "mattschrubb/zoneplus", version = "^3.2.0" }
CameraShaker = { wally = "brittonfischer/camerashaker", version = "^0.1.0" }
OctoTree = { wally = "sleitnick/octo-tree", version = "^0.3.1" }
ProfileService = { name = "avafe/profileservice", version = "^1.0.0" }
Chrono = { wally = "parihsz/chrono", version = "^1.0.8" }
