[package]
name = "jessekroeske/simplepath"
description = "SimplePath from grayzcale"
version = "2.2.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
